#!/usr/bin/env python3
"""Generate package/MarkdownEntities.roc from the HTML5 named character references.

CommonMark 0.31.2 section 2.5 recognises exactly the entity names of the HTML5
specification (https://html.spec.whatwg.org/entities.json). Python's
`html.entities.html5` is generated from that same table; only the names that end
with `;` are valid in CommonMark, so the legacy semicolon-less aliases are dropped.

The table is emitted as data (one string of `name` + NUL + `value` + NUL
records sorted by name, plus record offsets) and searched with a binary
search, which compiles much faster than a large `match`.

Usage: python3 scripts/markdown/gen_entities.py > package/MarkdownEntities.roc
"""

from __future__ import annotations

import html.entities


def roc_string(value: str) -> str:
    out = []
    for ch in value:
        code = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "$":
            out.append("\\$")
        elif code < 0x20 or code == 0x7F or code > 0x7E:
            out.append("\\u(%X)" % code)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main() -> None:
    entities = sorted(
        ((name[:-1].encode(), value) for name, value in html.entities.html5.items() if name.endswith(";")),
    )
    blob = []
    offsets = []
    position = 0
    for name, value in entities:
        offsets.append(position)
        record = name.decode() + "\x00" + value + "\x00"
        blob.append(record)
        position += len(record.encode("utf-8"))
    assert position < 65536, "offsets must fit in U16"

    lines = [
        "## GENERATED by scripts/markdown/gen_entities.py from the HTML5 named character",
        "## references (https://html.spec.whatwg.org/entities.json). Do not edit by hand.",
        "MarkdownEntities :: [].{",
        "",
        "\t## Decode an entity name (without `&` and `;`) to its replacement text.",
        "\tlookup : List(U8) -> Try(List(U8), [NotFound])",
        "\tlookup = |name| {",
        "\t\tvar $low = 0",
        "\t\tvar $high = offsets.len()",
        "\t\tvar $found = Err(NotFound)",
        "\t\twhile $low < $high {",
        "\t\t\tmiddle = ($low + $high) // 2",
        "\t\t\tstart = (offsets.get(middle) ?? 0).to_u64()",
        "\t\t\tmatch compare_name(name, start) {",
        "\t\t\t\tBefore => {",
        "\t\t\t\t\t$high = middle",
        "\t\t\t\t}",
        "\t\t\t\tAfter => {",
        "\t\t\t\t\t$low = middle + 1",
        "\t\t\t\t}",
        "\t\t\t\tSame => {",
        "\t\t\t\t\t$found = Ok(value_at(start + name.len() + 1))",
        "\t\t\t\t\t$low = $high",
        "\t\t\t\t}",
        "\t\t\t}",
        "\t\t}",
        "\t\t$found",
        "\t}",
        "}",
        "",
        "## Order `name` against the NUL-terminated record name at `start`.",
        "compare_name : List(U8), U64 -> [Before, Same, After]",
        "compare_name = |name, start| {",
        "\tvar $index = 0",
        "\tvar $result = Same",
        "\tvar $comparing = Bool.True",
        "\twhile $comparing {",
        "\t\tother = data.get(start + $index) ?? 0",
        "\t\tmine = if $index < name.len() (name.get($index) ?? 0) else 0",
        "\t\tif mine < other {",
        "\t\t\t$result = Before",
        "\t\t\t$comparing = Bool.False",
        "\t\t} else if mine > other {",
        "\t\t\t$result = After",
        "\t\t\t$comparing = Bool.False",
        "\t\t} else if mine == 0 {",
        "\t\t\t$comparing = Bool.False",
        "\t\t} else {",
        "\t\t\t$index = $index + 1",
        "\t\t}",
        "\t}",
        "\t$result",
        "}",
        "",
        "value_at : U64 -> List(U8)",
        "value_at = |start| {",
        "\tvar $end = start",
        "\twhile (data.get($end) ?? 0) != 0 {",
        "\t\t$end = $end + 1",
        "\t}",
        "\tdata.sublist({ start, len: $end - start })",
        "}",
        "",
        "offsets : List(U16)",
        "offsets = [" + ", ".join(str(o) for o in offsets) + "]",
        "",
        "data : List(U8)",
        "data = Str.to_utf8(" + roc_string("".join(blob)) + ")",
        "",
    ]
    print("\n".join(lines), end="")


if __name__ == "__main__":
    main()
