name: Tests

on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Roc version
        id: roc-version
        run: echo "nightly-tag=$(< .roc-version)" >> "$GITHUB_OUTPUT"

      - name: Install Roc
        uses: roc-lang/setup-roc@f5a74bf90aa694b43ab4a7cbfdb19273bc6aa697
        with:
          version: nightly-new-compiler
          nightly-tag: ${{ steps.roc-version.outputs.nightly-tag }}

      - run: roc version

      - run: ./ci/all_tests.sh
