name: Tests

on:
  pull_request:
  workflow_dispatch:

env:
  ZIG_VERSION: "0.16.0"

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          use-cache: false

      - name: Install Roc
        uses: roc-lang/setup-roc@main
        with:
          version: nightly-new-compiler

      - run: roc version

      - run: ./ci/all_tests.sh
